### ISSUE TITLE
Where do I find error logs (opac, intranet etc.)

### ISSUE THREAD

**Issue by grandmaestr** [jajm/koha-docker#1]
Hi, 

Where do I find the error logs? I searched and the instance doesn't seem to be writing any log files anywhere. Do they need to be enabled, and if so, how do I go about it?

Thanks!

**Comment by jajm** [comment]
Hi,

logs are all written on stderr, so you can see them with `docker logs CONTAINER`

You can modify `log4perl.conf` if you want logs to be written to files
