### ISSUE TITLE
How to use the koha scripts?

### ISSUE THREAD

**Issue by kaoz3000** [jajm/koha-docker#4]
Hi thank you for this Container!
I'm new to Koha and installed this for a friend.
I want to add a new language and I think should use "koha-translate"
but when i bash into the container and do
`~/koha$ ./debian/scripts/koha-translate`
it says: 
_Error: /usr/share/koha/bin/koha-functions.sh not present._
I copied all the files to this directory, but this gives the next error:
```
~/koha/debian/scripts$ ./koha-translate --list
ls: cannot access '/opac/htdocs/opac-tmpl/bootstrap/': No such file or directory
```

**Comment by jajm** [comment]
Hi,

These scripts only work when installing Koha with the .deb packages (see https://wiki.koha-community.org/wiki/Debian) which is not the case in the Docker image.
You should run the command: `misc/translator/translate install xx-XX` (where `xx-XX` should be replaced by the language code, eg. `fr-FR`)

If you need help regarding Koha, you should try the mailing lists or the IRC channel (https://koha-community.org/support/), lots of people can help you there ;)

**Comment by kaoz3000** [comment]
Thank you! This works perfectly!
I thought it might be a problem with the container, because the Koha Wiki suggested the script.
