### ISSUE TITLE
Build fails with DBD::mysql error

### ISSUE THREAD

**Issue by corgijan** [jajm/koha-docker#9]
When building on Linux (Arch) the following error occurs even if the fixed mysql-lib is added (see PR). 
```
! Installing the dependencies failed: Module 'DBD::mysql' is not installed
! Bailing out the installation for ..
288 distributions installed
```

Steps to reproduce: 
`docker-compose up` in 22.05

**Comment by jajm** [comment]
Fixed by d7cb411
